# Generated by Django 3.2.4 on 2021-06-04 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
